### ISSUE TITLE
How  to test my own dataset in the HADAR-network?

### ISSUE THREAD

**Issue by keke-2000** [FanglinBao/HADAR#13]
Hi, FanglinBao
     I am very interested in your work, but when I try to input my own hyperspectral data into the HADAR network for testing, I have a problem. I hope to input only hyperspectral data without other data, like T,e,v grountruth, but your code seems to load all these data while not only training and verification, but also testing, which makes me confused.

**Comment by keke-2000** [comment]
I have solved this problem, thanks

**Comment by keke-2000** [comment]
I have solved this problem, thanks

**Comment by hycPEXM** [comment]
Hi, I am wondering whether your own data is captured by a certain hyperspectral imager and how many channels the data contains? Do you directly used the author's TeX-Net python code to test your own data or you made some modifications to the original code, like the dataloader part? How about the results? Have you compared the TeX-Net results with TeX-SGD results？And do you successfully visualize the results(to get the TeX-vision)? I appreciate it if you're willing to answer my questions.

**Comment by keke-2000** [comment]
Hi, 
1.the testing hyperspectral dataset is generated by simulations, which contains 7 channels.
2.I do some modifications, add 'test_step' function in model.py
3.the result is bad, because my dataset is quite different from the HADAR dataset, like objects in them, so the Tex-Net's perfommance is poor.
4.I haven't done it, because SGD method is so slow, using near 20 hours on my computer.
5.yes

**Comment by keke-2000** [comment]
by the way, I graduated from NJU last year, hhh

**Comment by hycPEXM** [comment]
校友哈哈哈，感谢及时回复

**Comment by douCici** [comment]
@keke-2000 请问你有联系方式吗？我们可以交流一下。我的邮箱 cfx2010ep@hotmail.com

**Comment by M4N1S7** [comment]
> 顺便说一句，我去年从 NJU 毕业，hhh

我是今年nju的新生有一些问题想问问你我的邮箱：2556955325@qq.com
