### ISSUE TITLE
About Result Visualization

### ISSUE THREAD

**Issue by HollyYa** [FanglinBao/HADAR#14]
Hi jackygsb, the answer to the visualization section in the issue is now missing. I would like to ask if you could provide a more detailed explanation of the visualization methods after train and validation.

**Comment by FanglinBao** [comment]
Pls follow this instruction.
![image](https://github.com/FanglinBao/HADAR/assets/81270522/4c95aa61-f1a2-45f9-b265-c029dbedb882)
