### ISSUE TITLE
eMap mapping in GroundTruth

### ISSUE THREAD

**Issue by Daepilin** [FanglinBao/HADAR#17]
Hello Dr. Bao,

Thank you very much for sharing your very interesting work.

While trying to make the example matlab Code work I noticed that, in the ground truth, materials are mapped from some arbitrary (?) shuffled Indices to the order of materials as shown in the material namens DB.

Is there a specific reason why you did this? Is this baked into the scenes (by actually using eg iron emissivity for sky in some scenes) or just done for ground truth generation?

I ask, because I can not get the matlab Code to output expected materials (I teste for example Asphalt and sky pixels in scene 1) , and am wondering if I need to apply some mapping to the outputs?

**Comment by FanglinBao** [comment]
Hello Daepilin,

Thanks for your interest in our work.
When the scenes in the database were synthesized, each scene had its own subset of the material library, and each scene was synthesized independently by different artists. They were assigned global material indices in post processing for ground truth generation. That leads to the seemingly random shuffled indices.

**Comment by Daepilin** [comment]
Thank you very much for the quick response!

**Comment by Daepilin** [comment]
Thank you very much for the quick response!
