### ISSUE TITLE
Missing .npy files

### ISSUE THREAD

**Issue by SrahSrah** [FanglinBao/HADAR#18]
I'm trying to run main.py, but it's asking for '/Scene1/HeatCubes/S_EnvObj_L_0002.npy', the closest thing to this in the database provided is '/Scene1_Street/HeatCubes/L_0002_heatcube.mat'.

Is there a separate location I can find the .npy files? Or a function you used to convert between .mat and .npy?

Thanks!

**Comment by FanglinBao** [comment]
Hello Srah,
Please check this answer:
![image](https://github.com/FanglinBao/HADAR/assets/81270522/32497d09-aea0-4432-89ed-883384f08803)

**Comment by SrahSrah** [comment]
Thank you.

I was able to run preprocess_data.py after doing the following:

1. Downloading HADAR database
2. Renaming Folders from Scene1_Road to Scene1
3. Changing lines 58 and 59 in preprocess_data.py from
```
ids = [f"L_{i:04d}" for i in range(1, 5)]
ids += [f"R_{i:04d}" for i in range(1, 5)]

to:
ids = [f"{i:04d}" for i in range(1, 5)]
ids += [f"{i:04d}" for i in range(1, 5)]
```
