### ISSUE TITLE
S_EnvObj Generation unclear

### ISSUE THREAD

**Issue by Daepilin** [FanglinBao/HADAR#19]
Hello Dr. Bao,

Sorry first up for more questions. I spent the last weeks trying to get TexSdG working, and while your previous clarification about the Material mapping definitely helped, I'm still facing issues.

I ported the marlab Code over to python for my own experiments, but confirmed the optimization produces the same results (and all the steps in between as well). So far so good. (I can also recommend this, as some scipy optimizers are much quicker for me than matlab itself) 

I teste this on the real world Scene11 and got great results!

But on the simulated scene I simply cannot get all materials to properly 'estimate'.

Scene 7, first frame for example, most materials are correct but the trees and flowers/Grass tufts simply always come out as water. The Grass surfaces on the other Hand works fine.
![20231211_133437](https://github.com/FanglinBao/HADAR/assets/152170093/fc1cf0f6-91a9-41ce-b300-81e22a05e88f)
Please ingore Lack of textur, etc. I have not ported some of the visualization modes/details) 

As scene 11 works I think this must be due to the environment object estimation (or maybe temperature or radiance parameters, but I've tested a lot there and have similar results), as you provide a ground truth environment estimation for that scene (which I used for testing) 

Other scene Show similar errors with a few materials being categorically wrong. 

In your follow up "why are thermal images blurry" you weite that you use K-means to group environment objects and the average channel wise across each object. Do I understand that part correctly?

I get very clean clusters in the aforementioned scene (1 cluster being the sky and stones, the other being everything else) but I feel like I'm doing sth wrong still. 
![20231211_133310](https://github.com/FanglinBao/HADAR/assets/152170093/6bfc441d-58a2-4c23-9522-0bdd3e016a29)

I then take each cluster and calculate the mean for each of the 54 channels. 

Any idea on why this might not work as expected? 

Ps: I'm sorry I cannot post proper screenshots, these Photos are all I can provide.

**Comment by FanglinBao** [comment]
Hi Daepilin,

Thanks for sharing your thoughts about a python version of TeX-SGD. I'm definitely interested and want to have a test if you've released it somewhere.

Since you have good results for Scene 11. I think the error you met with synthetic scenes is not a bug of your codes. Environment estimation does matter. K-means clustering is the best solution we have for the moment, but there are many remaining aspects deserving further exploration.

For objects in crowded scenes, the non-uniformity of an object's environment starts to dominate over. In principle, more environmental terms are needed for crowded scenes (e.g., scene 7 or scene 1) than open scenes (like experimental scene 11 or synthetic scene 9). But 'with more environmental terms' immediately requires more spectral bands to solve the problem, and the solution is less robust (trapped in local minima). Also note that the synthetic data contains numeric error as well in Monte Carlo simulations (finite sampling).

We think using spatial+spectral information for TeX decomposition (i.e., TeX-Net) is a promising way to go in the future.

Hope this can help!

**Comment by Daepilin** [comment]
Definitely interesting input! Thanks for that! 

Unfortunately for scene 7 I could, even with 6 en objects, not quite reproduce correct results.

But your opinion and my experiments seem to confirm my idea that it's the environmental radiation and I will continue my investigations there. 

Except for temperature. The matlab example uses 10-20C for the real scene, but for simulated data this is obviously not correct. Would it be possible to know that range for those as well?


As for sharing code: I'm not sure i will be able to share everything, but I will do what I can when I can :) 

what I can say already is that I have good experiences using the scipy slsqp optimizer (maybe a bit more noisy than interior point but much much faster)

**Comment by FanglinBao** [comment]
Yes, you can check the tMap in the ground truth folder for the ground truth temperatures. You can set upper and lower bounds accordingly.
'Scipy slsqp optimizer' is the information I would like to know. That is sufficient. Thanks.

**Comment by Daepilin** [comment]
Glad I could provide some useful info. I'm also still experimenting with other optimizer algorithms but the final results seem very similar right now. 

Maybe 2 more things on this:

1) what did you use for estimating the environment in scene 11,if you can share thst info? I've compared the GT you provide with my own K-means and the estimations are quite significantly different. Do you provide your own cluster centers or do you use an automatic approach? 

2) Do you do further processing with the cluster means before using them in later steps? Right now I'm basically simply using
`cluster_idx = kmeans(reshape(HSI, [], 49) 2);`
`Env1 = mean(reshape(HSI, [], 49)(cluster_idx==1, :));`
`Env2 = mean(reshape(HSI, [], 49)(cluster_idx==2, :));`
`S_EnvObj = cat(1,Env1,Env2);
 `  (example what I tried for comparing your scene 11 GT with my Code) 

Of course this does not guarantee me which of the 2 (or more) clusters is the sky, but from my understanding thst is only relevant for visualization? 

Of course only if you want/can answer this. I know you wrote in other issues that you plan further releases so I dont want to pry too much.

**Comment by FanglinBao** [comment]
Yeah, we plan to confirm everything is correct and make the process more robust, before we can release it.
For Scene 11, mostly the sky is not included in the images. So, we estimated the sky radiance from the reflection of the checkerboard marker. 2 out of 4 squares of the marker are highly reflective and diffusive.

**Comment by Daepilin** [comment]
Thank you very much :)

**Comment by goodluckfory** [comment]
1. the input data provided by the author has a size of 1088*1920 I cropped it to a multiple of 16 to be able to train.
2. the loss becomes nan during the training process.
3. have you encountered this type of problem?

**Comment by chaunceywx** [comment]
> 2\. Env1

May I ask which part of the original code you are replacing with this code?

I fail to find the k-means related code in the  SGD_and_TeX_vision_matlab_code_package https://purdue0-my.sharepoint.com/:f:/g/personal/sjape_purdue_edu/EikkN6bcJJNLoAP-ks_DqVQBIzIrE_LnN8bGEjtlKz6jlA?e=UOAlvE

I'm not very good at matlab code. It would help me a lot if you could reply to me.

**Comment by chaunceywx** [comment]
> Glad I could provide some useful info. I'm also still experimenting with other optimizer algorithms but the final results seem very similar right now.
> 
> Maybe 2 more things on this:
> 
> 1. what did you use for estimating the environment in scene 11,if you can share thst info? I've compared the GT you provide with my own K-means and the estimations are quite significantly different. Do you provide your own cluster centers or do you use an automatic approach?
> 2. Do you do further processing with the cluster means before using them in later steps? Right now I'm basically simply using
>    `cluster_idx = kmeans(reshape(HSI, [], 49) 2);`
>    `Env1 = mean(reshape(HSI, [], 49)(cluster_idx==1, :));`
>    `Env2 = mean(reshape(HSI, [], 49)(cluster_idx==2, :));`
>    `S_EnvObj = cat(1,Env1,Env2);  `  (example what I tried for comparing your scene 11 GT with my Code)
> 
> Of course this does not guarantee me which of the 2 (or more) clusters is the sky, but from my understanding thst is only relevant for visualization?
> 
> Of course only if you want/can answer this. I know you wrote in other issues that you plan further releases so I dont want to pry too much.



May I ask which part of the original code you are replacing with this code?

I fail to find the k-means related code in the SGD_and_TeX_vision_matlab_code_package https://purdue0-my.sharepoint.com/:f:/g/personal/sjape_purdue_edu/EikkN6bcJJNLoAP-ks_DqVQBIzIrE_LnN8bGEjtlKz6jlA?e=UOAlvE

I'm not very good at matlab code. It would help me a lot if you could reply to me.

**Comment by Cyingyinging** [comment]
> 您好 Bao 博士，
> 
> 首先，我很抱歉有更多问题。我花了过去几周的时间试图让 TexSdG 正常工作，虽然您之前对材质映射的澄清确实有帮助，但我仍然面临问题。
> 
> 我将 marlab 代码移植到 python 进行自己的实验，但确认优化会产生相同的结果（以及介于两者之间的所有步骤）。 目前为止，一切都好。 （我也可以推荐这个，因为一些 scipy 优化器对我来说比 matlab 本身快得多）
> 
> 我在现实世界的 Scene11 上测试了这一点，并得到了很好的结果！
> 
> 但是在模拟场景中，我根本无法让所有材料都正确地“估计”。
> 
> 例如，场景 7，第一帧，大多数材质都是正确的，但树木和花朵/草簇总是以水的形式出现。另一方面，草地表面工作正常。![20231211_133437](https://private-user-images.githubusercontent.com/152170093/289537247-fc1cf0f6-91a9-41ce-b300-81e22a05e88f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MDA3ODAsIm5iZiI6MTczNjkwMDQ4MCwicGF0aCI6Ii8xNTIxNzAwOTMvMjg5NTM3MjQ3LWZjMWNmMGY2LTkxYTktNDFjZS1iMzAwLTgxZTIyYTA1ZTg4Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQwMDIxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGZlNzZmMDU2MGEwN2M2ZDgxZjNjZWM3YjMwMjQ4M2I5MWM1NmNjNTc1YTg1MDFiNGJmNDE2MWM3YTMwODc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i7rxD6eEyPRSU52mble0i5WTEPwljLPxcHzq425CVls)请 ingore 缺乏纹理等。我没有移植一些可视化模式/细节）
> 
> 由于场景 11 有效，我认为这一定是由于环境对象估计（或者可能是温度或辐射参数，但我在那里进行了大量测试并得到了类似的结果），因为您为该场景提供了真实环境估计（我用于测试）
> 
> 其他场景 显示类似的错误，但一些材质明显错误。
> 
> 在后续的“为什么热图像模糊”中，您提到使用 K-means 对环境对象和每个对象的平均通道进行分组。我正确理解了这部分吗？
> 
> 在上述场景中，我得到了非常干净的集群（一个集群是天空和石头，另一个集群是其他一切），但我觉得我仍然做错了。 ![20231211_133310](https://private-user-images.githubusercontent.com/152170093/289536793-6bfc441d-58a2-4c23-9522-0bdd3e016a29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MDA3ODAsIm5iZiI6MTczNjkwMDQ4MCwicGF0aCI6Ii8xNTIxNzAwOTMvMjg5NTM2NzkzLTZiZmM0NDFkLTU4YTItNGMyMy05NTIyLTBiZGQzZTAxNmEyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQwMDIxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjlhNzYxOTExOTExZTg2ZWNhZmQ1Yzg0NDk0MzE2MDIzYzkwZDk0MDE4ZWUxMGFjZDU0YzA4Y2RmNGMyMTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pTAsZqGy1fH2y2An8-XruurZQqidlgP5BTZydqTKcU0)
> 
> 然后，我获取每个聚类并计算 54 个通道中每个通道的平均值。
> 
> 知道为什么这可能无法按预期工作吗？
> 
> Ps：很抱歉，我无法发布适当的屏幕截图，这些照片是我能提供的。

Can you share python related code? I am currently replicating the code for this work. Or we could talk more. Thank you very much. Looking forward to your reply
