### ISSUE TITLE
Bugs of the dataset

### ISSUE THREAD

**Issue by cuge1995** [FanglinBao/HADAR#2]
when running training:
```
fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: HADAR_database/Scene1/HeatCubes/S_EnvObj_L_0002.npy
```

**Comment by cuge1995** [comment]
I've run the prepare_data.py, but Scene11 seems lost files:
```
Scene11/GroundTruth/eMap/eMap_L_0001.mat
```

**Comment by FanglinBao** [comment]
Hi cuge1995,
Thank you for your interest in our work.
You will need to run preprocess_data.py to get S_EnvObj_L_*.npy.
In Scene11, the files are named as eMap_0001.mat, without the letter 'L'.
Sorry for the inconvenience
