### ISSUE TITLE
TEX TO HSV

### ISSUE THREAD

**Issue by mengzhaoZ** [FanglinBao/HADAR#3]
Hello , I am a student from China, just finished reading your article, it is very helpful to me. I would like to ask you a question, how do you do the conversion from tex to hsv? Are there any more detailed descriptions in the code for these formulas as shown below
![image](https://github.com/FanglinBao/HADAR/assets/84321799/cf184bcf-03f7-4730-8648-21744f1b0664)

**Comment by FanglinBao** [comment]
Hi mengzhaoZ,
Thanks for your interest in our work.
Please check the matlab code TeX.Vision in the TeX-SGD code package. There are explicit codes for the transform.

**Comment by mengzhaoZ** [comment]
Hi, Mr. Bao,
Thank you very much for your reply. I will carefully look at the matlab code and learn it.

**Comment by xxnange** [comment]
So excited to receive the articl from pubplic platform, fer a question which is confusing me, what can the FPS of the input image account?  may be you could arrange your net on a  hardware device like ZYNQ, JESTON ORIGN ,EFINIX with soft ware 。your resarch will promoting the Revolution of Autonomous Driving  if the FPS and precision can be to a certain extent！ Thanks！
