### ISSUE TITLE
How to run the matlab code to get the complete data and run the successfully TeX-SGD (Semi-Global-Decomposition)  to get the results? 

### ISSUE THREAD

**Issue by jackygsb** [FanglinBao/HADAR#6]

**Comment by FanglinBao** [comment]
Hi jackygsb,
The code to generate the semantic library has not been released yet. I'm still improving that algorithm and it will be released along with follow-up papers.
The code and data in the HADAR paper starts from the obtained semantic library (matLib2.mat, HueLib2.mat, Idx_EnvObj.mat, S_EnvObj.mat).
You can run TeX.SGD following the instructions in mainTeX.m and it will return eMap/tMap/vMap

**Comment by jackygsb** [comment]
> Hi jackygsb, The code to generate the semantic library has not been released yet. I'm still improving that algorithm and it will be released along with follow-up papers. The code and data in the HADAR paper starts from the obtained semantic library (matLib2.mat, HueLib2.mat, Idx_EnvObj.mat, S_EnvObj.mat). You can run TeX.SGD following the instructions in mainTeX.m and it will return eMap/tMap/vMap
----------------------
-----------------------
Sorry. TeX.SGD still can not run due to lack of data. myTeX.SGD(tMap0,vMap0) needs the necessary data built on the previous step. However, in fold of test_TeX_AppData, there are no heatcube.mat data. If run  myTeX.loadHSI(), it will read heatcube.mat from HADAR databased. But as your indicated there are no code to generate the (matLib2.mat, HueLib2.mat, Idx_EnvObj.mat, S_EnvObj.mat) for the  heatcube.mat. The data in the fold of test_TeX_AppData are not corresponding to the heatcube.mat data processed by myTeX.loadHSI(). Could you please provide the complete code and data so that the TeX.SGD could be run? and return the results of eMap/tMap/vMap ?  Many thanks.

**Comment by FanglinBao** [comment]
Hi jackygsb, I'll check and update in a few days.

**Comment by FanglinBao** [comment]
Hi jackygsb, I've uploaded the test data. You can now download the TeX_matlab_code_package_with_test_data.zip file from the same link, unzip it, and run mainTeX.m

**Comment by jackygsb** [comment]
> Hi jackygsb, I've uploaded the test data. You can now download the TeX_matlab_code_package_with_test_data.zip file from the same link, unzip it, and run mainTeX.m

Hi Fanglin. Thanks for you reply. MainTex.m can run without problems. However, it is still difficult  to visualize the results of generated by TexNet.  The matlab code you provided seems to be very specific and can only run on the specific data you provided with matlab code.    My understanding is that Texnet generates T, e, V and other data as shown below, and the resmap data is generated by the visualization.py code? (e.g., residue_1_no_rescale.npy). I have saved the data generated by Texnet into .mat format. My question is how to input the above data results generated by TexNet into this matlab code , and visualize the results. Because, only in this way can we verify whether the program can get the correct result. However, I tried many times, Texnet generated T, e, V and other data that cannot be directly used for the input of matlab code and get the relative correct results as shown in the paper, there are many problems in the program due to the format of the data, dimensions are inconsistent, missing, etc..  Could you please provide the correct code and instructions？

![image](https://github.com/FanglinBao/HADAR/assets/63445522/0484cf81-6ce7-4be5-b6a1-47936ca8eb21)

![image](https://github.com/FanglinBao/HADAR/assets/63445522/708505d6-22d6-4b5c-9534-057e8d194390)

![image](https://github.com/FanglinBao/HADAR/assets/63445522/5f6c37fe-f88b-4ed6-bc9a-55c0c96936fa)

**Comment by FanglinBao** [comment]
[test.txt](https://github.com/FanglinBao/HADAR/files/12455347/test.txt)
Hi jackygsb,
I've attached here my previous matlab code to visualize the TeX vision from TeX-Net outputs, to help you configure the TeX object.
You will need to specify some path/names/parameters, though, for your specific case.
Hope this can help.

**Comment by jackygsb** [comment]
> [test.txt](https://github.com/FanglinBao/HADAR/files/12455347/test.txt) Hi jackygsb, I've attached here my previous matlab code to visualize the TeX vision from TeX-Net outputs, to help you configure the TeX object. You will need to specify some path/names/parameters, though, for your specific case. Hope this can help.

Thanks Fanglin. How, it is still can not run.  Index exceeds matrix dimensions. It seems lacking HueLib_full.mat and matLib_full.mat. Could you please provide these two ,mat and I will try again. Thanks
![image](https://github.com/FanglinBao/HADAR/assets/63445522/351218bc-3d3d-4fa5-b308-a98bbd94a281)

![image](https://github.com/FanglinBao/HADAR/assets/63445522/e1ad11de-0742-4602-9515-5ab25df35ebd)

![image](https://github.com/FanglinBao/HADAR/assets/63445522/9a5b056f-7608-43a7-9f33-7f80e0f89896)

**Comment by jackygsb** [comment]
> [test.txt](https://github.com/FanglinBao/HADAR/files/12455347/test.txt) Hi jackygsb, I've attached here my previous matlab code to visualize the TeX vision from TeX-Net outputs, to help you configure the TeX object. You will need to specify some path/names/parameters, though, for your specific case. Hope this can help.
I have tried to use the HueLib2.mat provided in the fold new_tex_matlab\test_TeX_AppData, but it didn't work (e.g., Index exceeds matrix dimensions.). I think that it may be the HueLib2.mat is wrong but need to use the  HueLib_full.mat and matLib_full.mat. 

![image](https://github.com/FanglinBao/HADAR/assets/63445522/6ed18c6d-9480-4197-9f48-a5a62f33433e)

**Comment by FanglinBao** [comment]
HubLib2 and matLib2 in the test folder are only for the test, corresponding to the experimental subset of the full database.
HubLib_full and matLib_full are given in the HADAR database folder, named as *Lib_fullDatabase.mat. You can copy and paste and rename them.

**Comment by LYHTZHANGJIANG** [comment]
Can you provide Python visualization code for TeX-Net outputs?

**Comment by jackygsb** [comment]
> HubLib2 and matLib2 in the test folder are only for the test, corresponding to the experimental subset of the full database. HubLib_full and matLib_full are given in the HADAR database folder, named as *Lib_fullDatabase.mat. You can copy and paste and rename them.

Hi Fanglin:
Thanks. It seems that the unsupervised loss (physics-based loss) could not work independently? I have tried to train the Tex-net only using the unsupervised loss. However, the results looks bad especially for producing eMap.  I am thinking about how to verify the performance of TEX-net without groundtruth data, and how to provide reference for subsequent research. In particular, you did not publish the detailed method of making heatcube and groundtruth, such as how the groundtruth emap that may highly dependent on  the the semantic library was obtained, and whether you can provide the corresponding code. Thanks.

**Comment by jackygsb** [comment]
> HubLib2 and matLib2 in the test folder are only for the test, corresponding to the experimental subset of the full database. HubLib_full and matLib_full are given in the HADAR database folder, named as *Lib_fullDatabase.mat. You can copy and paste and rename them.

Hi Fanglin:
If my understanding is correct, even TeX-SGD requires a lot of pre-knowledge, such as material library, number of object categories and other information. The overall feeling is that you must know the information of a specific scene to calculate its ground truth.

So for real scenes, for example, when we collect heatcube, we don't even know how many categories and other information are in the scene. How to get the results of TEX? Can the author provide a general program that can optimize the input heatcube based on the material library provided by author to obtain ground truth?

**Comment by FanglinBao** [comment]
> > HubLib2 and matLib2 in the test folder are only for the test, corresponding to the experimental subset of the full database. HubLib_full and matLib_full are given in the HADAR database folder, named as *Lib_fullDatabase.mat. You can copy and paste and rename them.
> 
> Hi Fanglin: If my understanding is correct, even TeX-SGD requires a lot of pre-knowledge, such as material library, number of object categories and other information. The overall feeling is that you must know the information of a specific scene to calculate its ground truth.
> 
> So for real scenes, for example, when we collect heatcube, we don't even know how many categories and other information are in the scene. How to get the results of TEX? Can the author provide a general program that can optimize the input heatcube based on the material library provided by author to obtain ground truth?

Hi jackygsb,

As stated in the paper,
"  The material library explains the physics but requires on-site collection/calibration. We have also provided a generalized HADAR theory that does not require an input of material library (see section SV.C of the Supplementary Information)...  "
We started with a material library to better explain how we implement the TeX decomposition. But we did have a generalized method called the 'semantic library' for real-world scenes where the environment is unknown. The semantic library, the number of categories, and the environmental radiations can be estimated from the data itself. We are working on a follow-up paper which has more details about this semantic library approach. I'll be able to share it once it's done.

**Comment by FanglinBao** [comment]
> > HubLib2 and matLib2 in the test folder are only for the test, corresponding to the experimental subset of the full database. HubLib_full and matLib_full are given in the HADAR database folder, named as *Lib_fullDatabase.mat. You can copy and paste and rename them.
> 
> Hi Fanglin: Thanks. It seems that the unsupervised loss (physics-based loss) could not work independently? I have tried to train the Tex-net only using the unsupervised loss. However, the results looks bad especially for producing eMap. I am thinking about how to verify the performance of TEX-net without groundtruth data, and how to provide reference for subsequent research. In particular, you did not publish the detailed method of making heatcube and groundtruth, such as how the groundtruth emap that may highly dependent on the the semantic library was obtained, and whether you can provide the corresponding code. Thanks.

Thanks for your continuing efforts to follow the results.
1. For the moment, we only have good results for supervised and hybrid learnings (hybrid loss). The completely unsupervised learning (physics-based loss) is more difficult, and we are still working on that. 
2. For synthetic scenes, the heatcube and the ground truth T/e maps are generated by path tracing (Blender). This is mentioned in the Methods. There is no code for this. For experimental scenes, the heatcube is collected by the hardware imager. We haven't released the code to generate the semantic library. We are still improving this part and will release it in follow-up papers.

**Comment by FanglinBao** [comment]
@jackygsb 
If you would like to, we can connect in some social apps for future discussions and sharing of latest results. I mainly use WeChat, but pls let me know if you can suggest an alternative app. You can email me. Thanks!

**Comment by FanglinBao** [comment]
> @jackygsb If you would like to, we can connect in some social apps for future discussions and sharing of latest results. I mainly use WeChat, but pls let me know if you can suggest an alternative app. You can email me. Thanks!

baof[at]purdue[dot]edu
