### ISSUE TITLE
Can you generate a traced model using pytorch jit for users to test?

### ISSUE THREAD

**Issue by shockwaveHe** [FanglinBao/HADAR#9]
Hi Dr. Bao, I am interested in your work and want to apply HADAR to some tasks. However, it looks like the documentation and packages are not fully developed, causing a big issue in testing and evaluating your work quickly. Is it possible for you to generate a traced model using the torch.jit.trace() method so that I can quickly test HADAR inference? Thanks! And also the configuration of mainTeX.m is not clear. There are no files with 's_EnvObj.mat' and '_wn' in the dataset you provide.

**Comment by FanglinBao** [comment]
Hi shockwaveHe,
Thanks for your interest in our work. I've updated the TeX code package. Please re-download and test. Also, please check issue #6 for some of the clarifications. Thanks.
